### ISSUE TITLE
Installation Woes. 

### ISSUE THREAD

**Issue by jAirbender** [ThinkUpLLC/ThinkUp#2279]
Hi Big fan of Gina and All about Android and TWIT listener. I have searched the message board and genuinely have put an earnest effort to try to install ThinkUp on my VPS. Sadly with no luck. 

[I Followed the Step By Step Installation Guide](https://www.thinkup.com/docs/install/install.html) But that was no good because that is Version 2.0Beta 10 and I kept getting the [Facebook Permission Issue](https://github.com/ThinkUpLLC/ThinkUp/issues/2246) 

So then as Gina suguests I install directly from the Master Branch, I downloaded it and installed from the webapp folder but then kept getting the [Database Error](https://github.com/ThinkUpLLC/ThinkUp/issues/2246) So again as Gina suggests, [Pulled From the Command line on a public HTML folder on my site](https://www.thinkup.com/docs/install/fromsource.html) and I keep getting an "make sure you have correct access rights and the repository exists" message. Do I need a public key or something? I really just want to install this great software on my server. 

If it's a money thing i'll sign up for the .com service but I really want to be able to run this from my server. 
![thinkup](https://cloud.githubusercontent.com/assets/16767687/12435679/f53c2c4c-bec3-11e5-8fe5-bbaafb4686b6.jpg)

Thanks for any and all assistance, 

Your Fellow Homo,
~Josh

**Comment by ginatrapani** [comment]
Hey Josh - sorry for all the trouble you're going through installing ThinkUp on your VPS. It would be way easier for you to sign up at ThinkUp.com - not a money thing, a convenience thing! 

Otherwise things might be broken, and you will have to submit your Facebook app for approval, etc. The truth is ThinkUp isn't that easy to run on your own server anymore.

That all said, if you still want to try, here's advice from GitHub on how to fix the "Permission denied (publickey)" message https://help.github.com/articles/error-permission-denied-publickey/
